# =============================================================================
# Docker Compose for Quizzical AI Local Development
# =============================================================================
# To run:   docker compose up --build
# To stop:  docker compose down
# =============================================================================

services:
  # ---------------------------------------------------------------------------
  # Frontend Service (React Application with Nginx)
  # ---------------------------------------------------------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quizzical-frontend
    ports:
      # Host 3000 -> Container 80 (matches backend CORS)
      - "3000:80"
    depends_on:
      - backend
    networks:
      - quizzical-network

  # ---------------------------------------------------------------------------
  # Backend Service (FastAPI Application)
  # ---------------------------------------------------------------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      # NOTE: No build args for APP_ENVIRONMENT here; it's runtime-provided.
    container_name: quizzical-backend
    env_file:
      # Primary local configuration source
      - ./.env
    environment:
      # Use Docker service names for internal DNS
      DATABASE__HOST: db
      REDIS__HOST: redis
    volumes:
      # Mount backend source for rapid iteration (matches previous behavior)
      - ./backend:/app
    depends_on:
      # Start backend only when db/redis are healthy
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      # Host 8000 -> Container 8000
      - "8000:8000"
    networks:
      - quizzical-network

  # ---------------------------------------------------------------------------
  # Database Service (PostgreSQL with pgvector)
  # ---------------------------------------------------------------------------
  db:
    image: pgvector/pgvector:0.8.0-pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quiz
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d:ro
    networks:
      - quizzical-network

  # ---------------------------------------------------------------------------
  # Cache Service (Redis)
  # ---------------------------------------------------------------------------
  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      - quizzical-network

# =============================================================================
# Networks
# =============================================================================
networks:
  quizzical-network:
    driver: bridge

# =============================================================================
# Named Volumes
# =============================================================================
volumes:
  pgdata:
