# =============================================================================
# Docker Compose for Quizzical AI Local Development
# =============================================================================
# To run:   docker compose up --build
# To stop:  docker compose down
# =============================================================================

services:
  # ---------------------------------------------------------------------------
  # Frontend Service (React Application with Nginx)
  # ---------------------------------------------------------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quizzical-frontend
    # Env at runtime (Nginx) is usually not needed, but we include for symmetry.
    # Note: Vite reads ./frontend/.env during the *build* step (handled in Dockerfile).
    env_file:
      - ./.env              # global defaults
      - ./frontend/.env     # frontend-specific overrides
    ports:
      - "3000:80"           # Host 3000 -> Container 80
    depends_on:
      - backend
    networks:
      - quizzical-network

  # ---------------------------------------------------------------------------
  # Backend Service (FastAPI Application)
  # ---------------------------------------------------------------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quizzical-backend
    env_file:
      - ./.env              # global defaults
      - ./backend/.env      # backend-specific overrides (wins if conflicts)
    environment:
      # Force container-internal hosts for service discovery
      DATABASE__HOST: db
      REDIS__HOST: redis
    volumes:
      - ./backend:/app      # hot reload/dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - quizzical-network

  # ---------------------------------------------------------------------------
  # Database Service (PostgreSQL with pgvector)
  # ---------------------------------------------------------------------------
  db:
    image: pgvector/pgvector:0.8.0-pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quiz
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d:ro
    networks:
      - quizzical-network

  # ---------------------------------------------------------------------------
  # Cache Service (Redis)
  # ---------------------------------------------------------------------------
  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      - quizzical-network

# =============================================================================
# Networks
# =============================================================================
networks:
  quizzical-network:
    driver: bridge

# =============================================================================
# Named Volumes
# =============================================================================
volumes:
  pgdata:
