version: "3.9"

# Local development: FastAPI backend, Postgres (pgvector), and Redis.
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      # Pass build-time args from .env (safe; no secrets required for local)
      args:
        - APP_CONFIG_ENDPOINT=${APP_CONFIG_ENDPOINT}
        - APP_ENVIRONMENT=${APP_ENVIRONMENT}
    env_file:
      - ./.env
    # Override service-internal hosts so the backend container connects to other containers
    environment:
      DATABASE__HOST: db
      REDIS__HOST: redis
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"

  db:
    image: pgvector/pgvector:0.8.0-pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quiz
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      # Persist database data across container restarts/rebuilds
      - pgdata:/var/lib/postgresql/data
      # Ensure pgvector is enabled on DB init
      - ./backend/db/init:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"

volumes:
  pgdata:
