# docker-compose.yaml
version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile   # Same image for dev & prod
      # Uncomment if you need a multi‑arch push: 
      # platform: linux/arm64
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app        # live‑reload during local dev
    env_file:
      - .env           # keep secrets out of the file
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  db:
    image: pgvector/pgvector:0.6.2-pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quiz
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
