# Local App Configuration (non-secrets)
# Mirrors what you'd store in Azure App Configuration
# (e.g., as a single blob under key "quizzical:appsettings" or as hierarchical keys)

quizzical:
  app:
    name: "Quizzical"
    environment: "local"        # local | dev | staging | prod
    debug: true

  feature_flags:
    flow_mode: "agent"          # "local" | "agent"

  cors:
    origins:
      - "http://localhost:5173"
      - "http://127.0.0.1:5173"

  project:
    api_prefix: "/api/v1"

  # Retrieval policy (central, applies to all agent tools)
  retrieval:
    policy: "media_only"        # off | media_only | auto
    allow_wikipedia: false      # gate Wikipedia usage
    allow_web: false            # gate general web search usage
    max_calls_per_run: 0        # hard cap per session/run (0 = no network)
    # optional allow-list for web_search; domains only, no scheme
    allowed_domains: []         # e.g., ["www.imdb.com","www.themoviedb.org"]

  quiz:
    min_characters: 4
    max_characters: 6
    baseline_questions_n: 5
    max_options_m: 4
    max_total_questions: 20
    min_questions_before_early_finish: 6
    early_finish_confidence: 0.9
    first_step_timeout_s: 60.0
    stream_budget_s: 30.0
    # Bound parallel LLM calls for character generation.
    # Set to null to auto-pick (bounded in code), or an integer >= 1.
    character_concurrency: 4

  agent:
    max_retries: 3

  llm:
    # Global per-call timeout used by parallel character creation (and reused by question gen)
    per_call_timeout_s: 30

    tools:
      initial_planner:
        model: "gpt-4o-mini"
        temperature: 0.2
        max_output_tokens: 800
        timeout_s: 18
        json_output: true

      character_list_generator:
        model: "gpt-4o-mini"
        temperature: 0.3
        max_output_tokens: 1200
        timeout_s: 18
        json_output: true

      synopsis_generator:
        model: "gpt-4o-mini"
        temperature: 0.2
        max_output_tokens: 600
        timeout_s: 18
        json_output: true

      profile_writer:
        model: "gpt-4o-mini"
        temperature: 0.4
        max_output_tokens: 1600
        timeout_s: 18
        json_output: true

      profile_improver:
        model: "gpt-4o-mini"
        temperature: 0.3
        max_output_tokens: 1600
        timeout_s: 18
        json_output: true

      character_selector:
        model: "gpt-4o-mini"
        temperature: 0.2
        max_output_tokens: 1000
        timeout_s: 18
        json_output: true

      question_generator:
        model: "gpt-4o-mini"
        temperature: 0.4
        max_output_tokens: 1200
        timeout_s: 60
        json_output: true

      next_question_generator:
        model: "gpt-4o-mini"
        temperature: 0.4
        max_output_tokens: 800
        timeout_s: 18
        json_output: true

      final_profile_writer:
        model: "gpt-4o-mini"
        temperature: 0.3
        max_output_tokens: 1000
        timeout_s: 18
        json_output: true

      safety_checker:
        model: "gpt-4o-mini"
        temperature: 0.0
        max_output_tokens: 200
        timeout_s: 10
        json_output: true

      error_analyzer:
        model: "gpt-4o-mini"
        temperature: 0.2
        max_output_tokens: 600
        timeout_s: 12
        json_output: true

      failure_explainer:
        model: "gpt-4o-mini"
        temperature: 0.2
        max_output_tokens: 500
        timeout_s: 12
        json_output: true

      image_prompt_enhancer:
        model: "gpt-4o-mini"
        temperature: 0.6
        max_output_tokens: 600
        timeout_s: 18
        json_output: true

      decision_maker:
        model: "gpt-4o-mini"
        temperature: 0.2
        max_output_tokens: 800
        timeout_s: 18
        json_output: true

      # Present for completeness; disabled by retrieval policy above.
      web_search:
        model: "o4-mini"
        temperature: 0.2
        max_output_tokens: 1200
        timeout_s: 20
        json_output: false
        effort: "low"
        allowed_domains: []   # will be overridden by retrieval.allowed_domains if provided
        user_location:
          type: "approximate"
          country: "US"
          city: "Seattle"
          region: "WA"
          timezone: "America/Los_Angeles"
        include_sources: true
        tool_choice: "auto"

    # Optional prompt overrides; if omitted, defaults are used from prompts.py
    prompts: {}

  # -------------------------------
  # Frontend app configuration
  # (served verbatim by GET /config)
  # -------------------------------
  frontend:
    theme:
      colors:
        primary: "0 121 174"
        secondary: "30 41 59"
        compliment: "0 121 174"
        accent: "234 179 8"
        bg: "238 242 255"
        card: "255 255 255"
        fg: "15 23 42"
        border: "226 232 240"
        muted: "148 163 184"
        ring: "129 140 248"
        neutral: "148 163 184"
      fonts:
        sans: "Inter, sans-serif"
        serif: "Nunito, sans-serif"
      fontSizes:
        body: "1rem"
        input: "1rem"
        button: "1rem"
        landingTitle: "2.25rem"
        landingSubtitle: "1.125rem"
      layout:
        landing:
          pagePtSm: "1.5rem"
          pagePtMd: "3rem"
          pagePtLg: "4rem"

          cardMaxW: "56rem"
          cardPadSm: "2rem"
          cardPadMd: "3rem"
          cardPadLg: "4rem"
          cardRadius: "1rem"
          cardShadow: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)"

          heroHSm: "6rem"
          heroHMd: "7rem"
          heroHLg: "8rem"

          spaceAfterHeroSm: "1.5rem"
          spaceAfterHeroMd: "2rem"
          titleMaxW: "42rem"
          subtitleMaxW: "38rem"

          spaceTitleToSubtitleSm: "1rem"
          spaceTitleToSubtitleMd: "1.25rem"
          spaceSubtitleToFormSm: "2.5rem"
          spaceSubtitleToFormMd: "3rem"

          formMaxW: "36rem"

          inputHeight: "2.5rem"
          pillGap: "0.75rem"
          pillPl: "1.25rem"
          pillBorder: "1px solid rgba(var(--color-muted), 0.55)"
          pillBg: "rgba(var(--color-card), 0.9)"
          ringAlpha: "0.2"

          submitSize: "2.5rem"

          blobSizeSm: "6rem"
          blobSizeMd: "7rem"
          blobSizeLg: "8rem"
          blobOpacity: "0.18"
          underlineWidth: "8rem"
          underlineHeight: "6px"
          underlineRadius: "9999px"

    content:
      appName: "Quizzical AI"
      landingPage:
        title: "Discover Your True Personality"
        subtitle: "A custom personality quiz in seconds for any topic"
        placeholder: "e.g., Gilmore Girls, Myers Briggs, 90s R&B..."
        buttonText: "Create My Quiz"
        examples: ["The Office", "Ancient Rome"]
        inputAriaLabel: "Quiz Topic"
        validation:
          minLength: "Must be at least {min} characters."
          maxLength: "Cannot exceed {max} characters."
      aboutPage:
        title: "About Quizzical AI"
        description: "Learn more about Quizzical AI and how it works."
      termsPage:
        title: "Terms of Service"
        description: "Read our terms and conditions for using Quizzical AI."
      privacyPolicyPage:
        title: "Privacy Policy"
        description: "Understand how we handle your data and privacy."
      footer:
        about:   { label: "About",   href: "/about" }
        terms:   { label: "Terms",   href: "/terms" }
        privacy: { label: "Privacy", href: "/privacy" }
        donate:  { label: "Donate",  href: "https://github.com/sponsors/your", external: true }
        copyright: "Quizzical AI"
      loadingStates:
        quiz: "Preparing your quiz..."
        question: "Thinking..."
        page: "Loading..."
      errors:
        title: "An Error Occurred"
        description: "Something went wrong. Please try again or return to the home page."
        requestTimeout: "The request timed out. It's taking longer than expected."
        quizCreationFailed: "We were unable to create your quiz at this time."
        categoryNotFound: "Sorry, we couldn't create a quiz for that category."
        resultNotFound: "This result could not be found."
        startOver: "Start Over"
        retry: "Try Again"
        home: "Go Home"

    limits:
      validation:
        category_min_length: 3
        category_max_length: 80

    apiTimeouts:
      default: 15000
      startQuiz: 60000
      poll:
        total: 60000
        interval: 1000
        maxInterval: 5000

    # Frontend treats 'features' as optional. Keep here (no defaults in code).
    features:
      turnstileEnabled: false
      turnstileSiteKey: ""   # (optionally overridden by env TURNSTILE_SITE_KEY)
