// Generate a TS sprite module (icon-id -> inline SVG string) for the FE
// prototype, from the recolored SVGs. Inlined SVG = ZERO extra HTTP requests
// and zero layout shift, the strongest load-time story (plan §6.4).
//
// Run: node build-sprite.mjs
// Out: ../../../frontend/src/proto/qaIconSprite.ts

import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const RECOLORED = join(__dirname, "recolored");
const OUT_DIR = join(__dirname, "..", "..", "..", "frontend", "src", "proto");
const OUT = join(OUT_DIR, "qaIconSprite.ts");

if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });

const files = readdirSync(RECOLORED).filter((f) => f.endsWith(".svg"));
const entries = files
  .map((f) => {
    const id = f.replace(/\.svg$/, "");
    // Collapse whitespace; make it a compact single-line literal. Keep the
    // viewBox/strokes intact (the SVG already carries them).
    const svg = readFileSync(join(RECOLORED, f), "utf8")
      .replace(/\s*\n\s*/g, " ")
      .replace(/>\s+</g, "><")
      .trim();
    return `  ${JSON.stringify(id)}: ${JSON.stringify(svg)},`;
  })
  .sort();

const ts = `// AUTO-GENERATED by specifications/prototype/icons/build-sprite.mjs — DO NOT EDIT.
// Brand-recolored Lucide (ISC) icons inlined for the Q&A image-enrichment
// PROTOTYPE. Inline SVG => zero extra HTTP requests, zero layout shift.
// Gated entirely behind VITE_PROTO_QA_ICONS (see QaIcon.tsx).
/* eslint-disable */
export const QA_ICON_SVG: Record<string, string> = {
${entries.join("\n")}
};

export type QaIconId = keyof typeof QA_ICON_SVG;
`;

writeFileSync(OUT, ts, "utf8");
console.log(`wrote ${files.length} icons -> ${OUT}`);
