// frontend/src/hooks/useQuizMedia.ts
//
// Polls `GET /quiz/{quizId}/media` while images are still being generated by
// the backend's FAL background tasks, and exposes the latest snapshot so the
// UI can surface images as they become available without ever blocking the
// user-visible quiz flow.
//
// Design notes:
// - Polling is opt-in via the `enabled` flag — callers should disable it
//   once the user navigates away from the synopsis screen.
// - Polling stops automatically once every expected image (synopsis +
//   characters when known) has resolved, so we don't hammer the API once
//   everything is in place.
// - The first request is fired immediately (no initial delay) so existing
//   images appear without a perceptible wait.
// - Network failures are swallowed by design — the next tick will retry. The
//   page must keep working even when this hook never resolves anything.
//
import { useCallback, useEffect, useRef, useState } from 'react';
import { getQuizMedia, type QuizMediaSnapshot } from '../services/apiService';

const IS_DEV = import.meta.env.DEV === true;

const DEFAULT_INTERVAL_MS = 2_000;
const DEFAULT_MAX_DURATION_MS = 60_000;

export interface UseQuizMediaOptions {
  /** Disable polling (e.g. once the user has navigated past the synopsis). */
  enabled?: boolean;
  /** Names whose images we expect; used to decide when polling can stop. */
  expectedCharacterNames?: readonly string[];
  /** Whether to wait for a synopsis image (default true). */
  expectSynopsisImage?: boolean;
  /** Whether to wait for a result image (default false; only useful on the result page). */
  expectResultImage?: boolean;
  /** Poll cadence in milliseconds (default 2000). */
  intervalMs?: number;
  /** Hard ceiling on how long to keep polling, in ms (default 60000). */
  maxDurationMs?: number;
}

export interface UseQuizMediaResult {
  snapshot: QuizMediaSnapshot | null;
  /** Convenience map: character name → resolved image URL (omits null entries). */
  characterImageMap: Record<string, string>;
}

function isComplete(
  snap: QuizMediaSnapshot | null,
  expectedNames: readonly string[],
  expectSynopsisImage: boolean,
  expectResultImage: boolean,
): boolean {
  if (!snap) return false;
  if (expectSynopsisImage && !snap.synopsisImageUrl) return false;
  if (expectResultImage && !snap.resultImageUrl) return false;
  if (expectedNames.length > 0) {
    const have = new Set(
      snap.characters.filter(c => !!c.imageUrl).map(c => c.name),
    );
    for (const name of expectedNames) {
      if (!have.has(name)) return false;
    }
  }
  return true;
}

export function useQuizMedia(
  quizId: string | null | undefined,
  {
    enabled = true,
    expectedCharacterNames = [],
    expectSynopsisImage = true,
    expectResultImage = false,
    intervalMs = DEFAULT_INTERVAL_MS,
    maxDurationMs = DEFAULT_MAX_DURATION_MS,
  }: UseQuizMediaOptions = {},
): UseQuizMediaResult {
  const [snapshot, setSnapshot] = useState<QuizMediaSnapshot | null>(null);

  // Refs so the polling loop sees the latest values without restarting.
  const expectedNamesRef = useRef<readonly string[]>(expectedCharacterNames);
  expectedNamesRef.current = expectedCharacterNames;
  const expectSynRef = useRef(expectSynopsisImage);
  expectSynRef.current = expectSynopsisImage;
  const expectResRef = useRef(expectResultImage);
  expectResRef.current = expectResultImage;

  const characterImageMap: Record<string, string> = {};
  if (snapshot) {
    for (const c of snapshot.characters) {
      if (c.imageUrl) characterImageMap[c.name] = c.imageUrl;
    }
  }

  const tick = useCallback(
    async (id: string, controller: AbortController): Promise<QuizMediaSnapshot | null> => {
      try {
        return await getQuizMedia(id, { signal: controller.signal });
      } catch (err: any) {
        // Aborted → caller is tearing down; bubble silently.
        if (err?.name === 'AbortError' || err?.code === 'aborted') return null;
        if (IS_DEV) console.warn('[useQuizMedia] tick failed', err?.message ?? err);
        return null;
      }
    },
    [],
  );

  useEffect(() => {
    if (!enabled || !quizId) {
      setSnapshot(null);
      return;
    }

    const controller = new AbortController();
    const startedAt = Date.now();
    let timer: number | null = null;
    let cancelled = false;

    const schedule = () => {
      if (cancelled) return;
      timer = window.setTimeout(run, intervalMs);
    };

    const run = async () => {
      if (cancelled) return;
      const next = await tick(quizId, controller);
      if (cancelled) return;
      if (next) setSnapshot(next);

      const elapsed = Date.now() - startedAt;
      const done = isComplete(
        next,
        expectedNamesRef.current,
        expectSynRef.current,
        expectResRef.current,
      );
      if (done || elapsed >= maxDurationMs) return;
      schedule();
    };

    // Fire immediately so cached images appear without waiting for the first
    // interval tick.
    void run();

    return () => {
      cancelled = true;
      if (timer !== null) window.clearTimeout(timer);
      controller.abort();
    };
    // `expectedCharacterNames`, `expectSynopsisImage`, and `expectResultImage`
    // are intentionally read via refs so changes don't restart polling.
  }, [enabled, quizId, intervalMs, maxDurationMs, tick]);

  return { snapshot, characterImageMap };
}
