"""De-stubbed icon-index build step.

Replaces the prototype's static binding file with a REAL, runnable build that:
  1. Embeds every icon caption with the concrete 384-dim embed_fn (embed_fn.py).
  2. Writes an `icon_index.json` (id, concept, lucide, caption, 384-dim embedding,
     palette variant) — the content the proposed `icon_assets` table holds.
  3. Emits `migrations/0001_icon_assets.sql` — the additive table + IVFFlat cosine
     index in the EXACT shape the repo already uses for topics/session_history
     (`USING ivfflat (embedding vector_cosine_ops) WITH (lists=100)`), plus the
     INSERTs to seed it. This is the missing data-model piece (plan §4.3 Option A).

Run:  python pipeline/build_icon_index.py
"""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROTO = HERE.parent
DATA = PROTO / "data"
MIG = HERE / "migrations"

# palette variant by semantic role (mirrors recolor.mjs assignment intent)
INDIGO = {"brain", "lightbulb", "atom", "dna", "calculator", "code", "cpu", "puzzle",
          "chess", "graduation", "flask", "microscope", "robot"}
AMBER = {"fire", "zap", "balloon", "gift", "cake", "pizza", "icecream", "trophy",
         "medal", "star", "smile", "guitar", "music", "gamepad", "gamepad3", "dice"}
SLATE = {"cog", "wrench", "hammer", "key", "lock", "search", "scissors", "clock",
         "calendar", "briefcase", "mail", "phone", "smartphone", "shoppingcart"}


def variant_for(icon_id: str) -> str:
    if icon_id in INDIGO:
        return "indigo"
    if icon_id in AMBER:
        return "amber"
    if icon_id in SLATE:
        return "slate"
    return "sea"  # default brand primary


def sql_vector_literal(vec: list[float]) -> str:
    return "[" + ",".join(f"{x:.6f}" for x in vec) + "]"


def main() -> None:
    from embed_fn import embed_many_sync, MODEL_NAME, DIM  # noqa: E402
    import sys
    sys.path.insert(0, str(HERE))

    catalog = json.loads((DATA / "icon_catalog.json").read_text(encoding="utf-8"))["icons"]
    captions = [ic["rich_caption"] for ic in catalog]
    vecs = embed_many_sync(captions)

    index = []
    for ic, v in zip(catalog, vecs):
        index.append({
            "id": ic["id"],
            "lucide": ic["lucide"],
            "concept": ic["concept"],
            "caption": ic["rich_caption"],
            "palette_variant": variant_for(ic["id"]),
            "embedding": v,  # 384-dim, unit-norm
        })
    (DATA / "icon_index.json").write_text(json.dumps({
        "model": MODEL_NAME, "dim": DIM, "n_icons": len(index), "icons": index,
    }, indent=2), encoding="utf-8")

    # --- emit the additive migration (plan §4.3 Option A) ---
    MIG.mkdir(exist_ok=True)
    lines = [
        "-- icon_assets: brand-recolored icon library + 384-dim caption embedding.",
        "-- Additive, mirrors topics/session_history vector shape exactly.",
        "-- (prototype-generated by pipeline/build_icon_index.py)",
        "",
        "CREATE EXTENSION IF NOT EXISTS vector;",
        "",
        "CREATE TABLE IF NOT EXISTS icon_assets (",
        "  id               TEXT PRIMARY KEY,           -- stable icon id (e.g. 'rocket')",
        "  lucide_name      TEXT NOT NULL,              -- source open-set glyph name",
        "  concept          TEXT NOT NULL,              -- human concept label",
        "  caption          TEXT NOT NULL,              -- rich caption that was embedded",
        "  palette_variant  TEXT NOT NULL,              -- sea|indigo|amber|slate",
        "  source_set       TEXT NOT NULL DEFAULT 'lucide',",
        "  license          TEXT NOT NULL DEFAULT 'ISC',",
        "  storage_uri      TEXT NULL,                  -- CDN/blob path for the <img> path",
        "  embedding        VECTOR(384) NOT NULL,       -- same space as topics.embedding",
        "  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()",
        ");",
        "",
        "-- IVFFlat cosine index, identical pattern to topics.embedding / session_history.",
        "CREATE INDEX IF NOT EXISTS icon_assets_embedding_ivfflat",
        "  ON icon_assets USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);",
        "",
        "-- Seed rows (embeddings precomputed at build time; embed once, ever).",
    ]
    for it in index:
        lit = sql_vector_literal(it["embedding"])
        cap = it["caption"].replace("'", "''")
        concept = it["concept"].replace("'", "''")
        lines.append(
            f"INSERT INTO icon_assets (id, lucide_name, concept, caption, palette_variant, embedding) "
            f"VALUES ('{it['id']}', '{it['lucide']}', '{concept}', '{cap}', "
            f"'{it['palette_variant']}', '{lit}') ON CONFLICT (id) DO NOTHING;"
        )
    (MIG / "0001_icon_assets.sql").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"wrote data/icon_index.json ({len(index)} icons, {DIM}-dim)")
    print(f"wrote pipeline/migrations/0001_icon_assets.sql "
          f"({len(index)} seed INSERTs + IVFFlat index)")
    from collections import Counter
    print("palette variants:", dict(Counter(it["palette_variant"] for it in index)))


if __name__ == "__main__":
    import sys
    sys.path.insert(0, str(HERE))
    main()
