// src/store/quizStore.ts
import { create } from 'zustand';
import { devtools } from 'zustand/middleware';
import { useShallow } from 'zustand/react/shallow';
import type { StateCreator } from 'zustand';
import type { Question, Synopsis } from '../types/quiz';
import type { ResultProfileData } from '../types/result';
import * as api from '../services/apiService';
import {
  isWrappedQuestion,
  isWrappedSynopsis,
  isRawQuestion,
  isRawSynopsis,
  toUiQuestionFromApi,
  toUiCharacters,
  toUiResult,
} from '../utils/quizGuards';
import type { InitialPayload } from '../utils/quizGuards';
import {
  getQuizId,
  saveQuizId,
  clearQuizId,
  saveQuizState,
  getQuizState,
  type QuizStateSnapshot,
} from '../utils/session';
import type { ApiError } from '../types/api';
import { track } from '../services/analytics';

const IS_DEV = import.meta.env.DEV === true;

const MAX_RETRIES = 3;
const RETRY_DELAY_MS = 1500;
// AC-FE-PERF-POLL-2 (Phase 7): hard cap on any single re-poll delay so a
// hostile or buggy upstream cannot strand the FE for minutes.
const MAX_POLL_DELAY_MS = 10_000;
const MIN_SESSION_PERSIST_INTERVAL_MS = 1000;

/**
 * AC-FE-PERF-POLL-1 — clamp a re-poll delay to [base, MAX_POLL_DELAY_MS].
 * Honours `retryAfterMs` from the server (e.g. 429 Retry-After) but never
 * exceeds the hard cap.
 */
function clampPollDelay(baseMs: number, retryAfterMs?: number | null): number {
  const candidate = Math.max(baseMs, retryAfterMs ?? 0);
  return Math.min(MAX_POLL_DELAY_MS, Math.max(0, candidate));
}

/**
 * AC-FE-RELY-POLL-2 — exponential backoff with jitter for consecutive
 * 5xx / network failures. The next delay is
 *   ``min(MAX_POLL_DELAY_MS, baseMs * 2 ** (streak - 1)) + jitter[0, 250)``
 * Server `Retry-After` (passed via ``retryAfterMs``) always wins over the
 * computed backoff (still subject to the MAX clamp).
 */
function failureBackoffDelay(
  streak: number,
  baseMs: number,
  retryAfterMs?: number | null,
): number {
  const safeStreak = Math.max(1, streak);
  const exp = baseMs * Math.pow(2, safeStreak - 1);
  const jitter = Math.random() * 250;
  const computed = Math.min(MAX_POLL_DELAY_MS, exp) + jitter;
  return clampPollDelay(computed, retryAfterMs);
}

/**
 * AC-FE-POLL-PROD-1: single-flight polling. Module-scoped controller is aborted
 * on reset() or when a new beginPolling() supersedes the previous one.
 */
let activePollController: AbortController | null = null;

function abortActivePoll(reason?: string): void {
  if (activePollController) {
    try {
      activePollController.abort(reason ?? 'superseded');
    } catch {
      /* noop */
    }
    activePollController = null;
  }
}

export function __getActivePollControllerForTest(): AbortController | null {
  return activePollController;
}

type QuizStatus = 'idle' | 'loading' | 'active' | 'finished' | 'error';
type QuizView = 'idle' | 'synopsis' | 'question' | 'result' | 'error';

/**
 * Deep-review #14 — the synopsis screen is generated by a PAID agent run, but
 * `/quiz/status` has no synopsis shape (only processing/question/result). So a
 * synopsis-phase refresh cannot be recovered by polling — recovery would poll
 * `processing` into a fatal 60s-timeout loop and discard the paid synopsis +
 * characters. We instead persist the synopsis `viewData` in the session
 * snapshot and restore it LOCALLY on recovery, resuming at the synopsis screen
 * with zero network calls.
 *
 * The extra `synopsis` field rides on top of the base `QuizStateSnapshot`
 * (session.ts persists/returns the JSON opaquely, preserving unknown keys), so
 * no change to `session.ts` is needed.
 */
interface PersistedSnapshot extends QuizStateSnapshot {
  synopsis?: (Synopsis & { characters?: unknown }) | null;
  /**
   * "Try a different interpretation" (2026-07-02): the original typed topic +
   * the interpretation readings rejected so far. Persisted with the synopsis
   * snapshot so the reload affordance survives a refresh (session.ts stores
   * the JSON opaquely, preserving unknown keys — no session.ts change needed).
   */
  category?: string | null;
  rejectedInterpretations?: string[];
}

interface QuizState {
  status: QuizStatus;
  currentView: QuizView;
  viewData: Synopsis | Question | ResultProfileData | null;

  quizId: string | null;

  knownQuestionsCount: number;
  answeredCount: number;

  totalTarget: number;

  uiError: string | null;
  /**
   * Whimsical-error-system (2026-06-30) — the precise `QF-...` code for the
   * current fatal error (when the backend supplied one), shown as light-grey
   * small text below the message. Null when there is no error or no code.
   */
  uiErrorCode: string | null;
  /** Backend-echoed trace id for the current error (support log correlation). */
  uiErrorTraceId: string | null;
  isSubmittingAnswer: boolean;

  isPolling: boolean;
  retryCount: number;
  /**
   * AC-FE-RELY-POLL-1/2 — count of consecutive 5xx / network failures during
   * polling. Reset to 0 on every successful poll. Used to scale exponential
   * backoff and to decide when to give up (>= MAX_RETRIES).
   */
  pollFailureStreak: number;
  lastPersistTime: number;
  sessionRecovered: boolean;

  /**
   * Blackbox fix #4(b) — async image URLs persisted in the store so they SURVIVE
   * a view change (synopsis → question → result). Previously the media snapshot
   * lived only inside the synopsis-scoped `useQuizMedia` hook, so late-arriving
   * cast images were discarded when the user proceeded — the cast "never loaded"
   * by the time the result page rendered. The store is the single durable home
   * for these, merged additively as the poller resolves them; URLs are never
   * overwritten with null once known.
   */
  characterImages: Record<string, string>;
  synopsisImageUrl: string | null;
  resultImageUrl: string | null;

  /**
   * "Try a different interpretation" (owner blackbox, 2026-07-02) — the
   * original typed topic for the current quiz flow. Needed so the synopsis
   * screen's subtle reload affordance can start a NEW quiz for the SAME topic
   * with the prior reading(s) rejected.
   */
  category: string | null;
  /**
   * Interpretation readings ("<title> — <summary>") the user has rejected for
   * `category` so far in this flow. Accumulates across reload cycles and is
   * sent with each reinterpret so the planner never repeats a rejected one.
   */
  rejectedInterpretations: string[];
  /** In-flight guard for the reinterpret call (blocks double-clicks). */
  isReinterpreting: boolean;
}

interface QuizActions {
  startQuiz: (category: string, turnstileToken: string) => Promise<void>;
  /**
   * "Try a different interpretation" (2026-07-02) — start a NEW quiz for the
   * SAME typed topic, rejecting the currently displayed synopsis reading (and
   * every previously rejected one). Shows the normal loading state; on arrival
   * the new synopsis replaces the old. Errors restore the previous synopsis
   * with an inline message — never a dead end.
   */
  reinterpret: (turnstileToken: string) => Promise<void>;
  hydrateFromStart: (payload: {
    quizId: string;
    initialPayload: InitialPayload;
    charactersPayload?: { type: 'characters'; data: any[] } | null;
  }) => void;
  hydrateStatus: (dto: api.QuizStatusDTO) => void;
  beginPolling: (options?: { reason?: string }) => Promise<void>;
  markAnswered: () => void;
  submitAnswerStart: () => void;
  submitAnswerEnd: () => void;
  setError: (
    message: string,
    isFatal?: boolean,
    meta?: { code?: string | null; traceId?: string | null },
  ) => void;
  clearError: () => void;
  recover: () => void;
  reset: () => void;
  persistToSession: () => void;
  recoverFromSession: () => Promise<boolean>;
  /**
   * Blackbox fix #4(b) — merge a media snapshot's resolved image URLs into the
   * store. Additive only: a URL is set once known and never cleared by a later
   * snapshot that lacks it, so late-arriving cast images survive a view change
   * and show through to the result page.
   */
  mergeMediaSnapshot: (snapshot: {
    synopsisImageUrl?: string | null;
    resultImageUrl?: string | null;
    characters?: ReadonlyArray<{ name: string; imageUrl: string | null }>;
  } | null) => void;
}

type QuizStore = QuizState & QuizActions;

const initialState: QuizState = {
  status: 'idle',
  currentView: 'idle',
  viewData: null,
  // Deep-review #3: do NOT prefill `quizId` from sessionStorage here. Capturing
  // `getQuizId()` into the shared `initialState` object made the module-load
  // recovery guard (`!store.quizId`) permanently false, so session recovery
  // never ran and a mid-quiz refresh dead-ended on an eternal LoadingCard. The
  // store now boots with `quizId: null` and the module-load hook explicitly
  // drives `recoverFromSession()` when a saved quizId exists.
  quizId: null,
  knownQuestionsCount: 0,
  answeredCount: 0,
  totalTarget: 20,
  uiError: null,
  uiErrorCode: null,
  uiErrorTraceId: null,
  isSubmittingAnswer: false,
  isPolling: false,
  retryCount: 0,
  pollFailureStreak: 0,
  lastPersistTime: 0,
  sessionRecovered: false,
  characterImages: {},
  synopsisImageUrl: null,
  resultImageUrl: null,
  category: null,
  rejectedInterpretations: [],
  isReinterpreting: false,
};

/* -----------------------------------------------------------------------------
 * Normalizers
 * ---------------------------------------------------------------------------*/

function normalizeResultLike(raw: any): ResultProfileData {
  // If it's already UI-shaped, don't re-map.
  if (raw && (raw.profileTitle || raw.summary || raw.traits || raw.imageUrl)) {
    return raw as ResultProfileData;
  }

  // Otherwise, handle both wrapped and direct backend shapes.
  const d = raw && raw.data ? raw.data : raw;
  return toUiResult(d);
}

function normalizeQuestionLike(raw: any): Question {
  // ✅ Key fix: if it's already in UI shape (has `answers`), return as-is.
  if (raw && Array.isArray(raw.answers)) {
    return raw as Question;
  }
  // Otherwise, convert API/legacy shapes with `options` → `answers`.
  return toUiQuestionFromApi(raw);
}

function normalizeSynopsisLike(raw: any): Synopsis {
  const s = raw?.data ?? raw ?? {};
  return {
    title: String(s?.title ?? ''),
    summary: String(s?.summary ?? ''),
  };
}

/* -----------------------------------------------------------------------------
 * Store
 * ---------------------------------------------------------------------------*/

const storeCreator: StateCreator<QuizStore> = (set, get) => ({
  ...initialState,

  startQuiz: async (category: string, turnstileToken: string) => {
    // Deep-review #5: abort any in-flight poll from a PRIOR quiz before we
    // create a new one. Otherwise the old quiz's poll can resolve after the new
    // quizId is installed and hijack the new quiz with a stale question/result
    // (answers then post against the wrong quizId). The identity check in
    // doPoll is the second line of defence.
    abortActivePoll('new-quiz');
    clearQuizId();
    // Record the typed topic for the synopsis screen's "try a different
    // interpretation" reload; a fresh topic starts a fresh rejection chain.
    set({ ...initialState, quizId: null, status: 'loading', category, rejectedInterpretations: [] });
    try {
      const { quizId, initialPayload, charactersPayload } = await api.startQuiz(
        category,
        turnstileToken
      );
      // Funnel: a quiz was successfully created (top of the funnel). No PII —
      // we intentionally do not send the category text.
      track('quiz_start');
      get().hydrateFromStart({ quizId, initialPayload, charactersPayload });
    } catch (err) {
      if (IS_DEV) console.warn('[QuizStore] startQuiz handled error', err);
      const apiError = err as ApiError;
      // Whimsical-error-system (2026-06-30): prefer the backend's on-brand
      // `whimsical` copy + carry the precise `QF-...` code + trace id so the
      // error view can render the friendly message with the light-grey code.
      const message =
        apiError?.whimsical ||
        apiError?.message ||
        'Could not create a quiz. Please try again.';
      set({
        status: 'error',
        uiError: message,
        uiErrorCode: apiError?.qfCode ?? null,
        uiErrorTraceId: apiError?.traceId ?? null,
        currentView: 'error',
      });
      throw err;
    }
  },

  reinterpret: async (turnstileToken: string) => {
    const state = get();
    const { category, currentView, viewData, isReinterpreting } = state;
    // Only meaningful from the synopsis screen of a known topic, one at a time.
    if (!category || currentView !== 'synopsis' || isReinterpreting) return;

    const previousSynopsis = viewData as (Synopsis & { characters?: unknown }) | null;
    const title = previousSynopsis?.title?.trim() ?? '';
    const summary = previousSynopsis?.summary?.trim() ?? '';
    const rejectedLabel = title ? (summary ? `${title} — ${summary}` : title) : null;
    const nextRejected = rejectedLabel
      ? [...state.rejectedInterpretations, rejectedLabel]
      : [...state.rejectedInterpretations];

    // Supersede any in-flight poll for the outgoing quiz. NOTE: the old quizId
    // stays installed until the new one arrives — clearing it here would trip
    // QuizFlowPage's "missing quizId → navigate home" guard mid-reload.
    abortActivePoll('reinterpret');
    set({
      status: 'loading',
      // 'idle' view renders the normal LoadingCard on QuizFlowPage.
      currentView: 'idle',
      viewData: null,
      isReinterpreting: true,
      uiError: null,
      uiErrorCode: null,
      uiErrorTraceId: null,
    });

    try {
      const { quizId, initialPayload, charactersPayload } = await api.startQuiz(
        category,
        turnstileToken,
        { rejectedInterpretations: nextRejected }
      );
      // Same funnel event as a normal start (allow-listed set); a reinterpret
      // IS a new quiz. Commit the grown rejection list only on success so a
      // failed attempt doesn't double-count the same reading next time.
      track('quiz_start');
      set({ rejectedInterpretations: nextRejected });
      get().hydrateFromStart({ quizId, initialPayload, charactersPayload });
    } catch (err) {
      if (IS_DEV) console.warn('[QuizStore] reinterpret handled error', err);
      const apiError = err as ApiError;
      // Restore the previous synopsis (never dead-end a working quiz) and
      // surface the message inline on the synopsis view.
      set({
        status: 'active',
        currentView: 'synopsis',
        viewData: previousSynopsis,
        uiError:
          apiError?.whimsical ||
          apiError?.message ||
          'We couldn’t find another read on that topic. Please try again.',
        uiErrorCode: apiError?.qfCode ?? null,
        uiErrorTraceId: apiError?.traceId ?? null,
      });
    } finally {
      set({ isReinterpreting: false });
    }
  },

  hydrateFromStart: ({ quizId, initialPayload, charactersPayload }) => {
    // Deep-review #5: installing a NEW quizId must supersede any in-flight poll
    // from a previous quiz (hydrateFromStart is also reachable directly, not
    // only via startQuiz). A late snapshot from the old poll would otherwise
    // overwrite this fresh synopsis/question.
    abortActivePoll('new-quiz');
    saveQuizId(quizId);

    set((state) => {
      let view: QuizView = 'idle';
      let data: any = null;
      let knownQuestionsCount = 0;

      if (isWrappedQuestion(initialPayload)) {
        view = 'question';
        data = normalizeQuestionLike(initialPayload.data);
        knownQuestionsCount = 1;
      } else if (isWrappedSynopsis(initialPayload)) {
        view = 'synopsis';
        data = normalizeSynopsisLike(initialPayload.data);
      } else if (isRawQuestion(initialPayload)) {
        view = 'question';
        data = normalizeQuestionLike(initialPayload);
        knownQuestionsCount = 1;
      } else if (isRawSynopsis(initialPayload)) {
        view = 'synopsis';
        data = normalizeSynopsisLike(initialPayload);
      } else if (IS_DEV) {
        console.error(
          '[QuizStore] hydrateFromStart received invalid initialPayload',
          initialPayload
        );
      }

      if (view === 'synopsis' && data) {
        const validCharacters =
          !!charactersPayload &&
          charactersPayload.type === 'characters' &&
          Array.isArray(charactersPayload.data);
        if (validCharacters) {
          data = { ...data, characters: toUiCharacters(charactersPayload.data) };
        } else if (charactersPayload && IS_DEV) {
          console.warn(
            '[QuizStore] charactersPayload present but invalid shape',
            charactersPayload
          );
        }
      }

      const newState: QuizState = {
        ...state,
        quizId,
        status: 'active',
        currentView: view,
        viewData: data,
        knownQuestionsCount,
        answeredCount: 0,
        uiError: null,
        uiErrorCode: null,
        uiErrorTraceId: null,
        retryCount: 0,
      };

      setTimeout(() => get().persistToSession(), 0);
      return newState;
    });
  },

  hydrateStatus: (dto) => {
    if (!dto) return;

    if (dto.status === 'finished' && dto.type === 'result') {
      // Funnel: fire `quiz_complete` exactly once, on the transition into the
      // finished state (guard against repeated polls re-emitting it).
      const wasFinished = get().status === 'finished';
      set({
        status: 'finished',
        currentView: 'result',
        viewData: normalizeResultLike(dto.data),
        isPolling: false,
        retryCount: 0,
        // Deep-review #7/#8: a successful poll clears any stale transient poll
        // error so the finished view never renders a leftover inline error.
        uiError: null,
        uiErrorCode: null,
        uiErrorTraceId: null,
      });
      if (!wasFinished) track('quiz_complete');
      setTimeout(() => get().persistToSession(), 0);
      return;
    }

    if (dto.status === 'active' && dto.type === 'question') {
      const question = normalizeQuestionLike(dto.data);
      const servedNumber = (question as Question)?.questionNumber;

      // Deep-review #6: refuse to REPLACE an UNANSWERED on-screen question with
      // one that skips past it. If a poll fires while the user is still on a
      // question they have not answered, the BE can serve n+1
      // (max(answered_idx, known_questions_count)); applying it would swap the
      // question under the user and misattribute their next click.
      //
      // The discriminator is the DISPLAYED question vs `answeredCount`, NOT the
      // incoming one — otherwise a legitimate server advance (the FE counter
      // drifting behind, see #4) would be wrongly refused. The displayed
      // question is "unanswered" when `answeredCount < displayedNumber` (its
      // 0-based index equals `answeredCount`). We only refuse when the incoming
      // question is strictly AHEAD of that displayed one.
      const current = get();
      const displayedNumber = (current.viewData as Question | null)?.questionNumber;
      const displayedIsUnanswered =
        typeof displayedNumber === 'number' && current.answeredCount < displayedNumber;
      if (
        current.currentView === 'question' &&
        typeof servedNumber === 'number' &&
        typeof displayedNumber === 'number' &&
        displayedIsUnanswered &&
        servedNumber > displayedNumber
      ) {
        if (IS_DEV) {
          console.warn('[QuizStore] hydrateStatus refused skip-ahead question', {
            servedNumber,
            displayedNumber,
            answeredCount: current.answeredCount,
          });
        }
        // Not fatal, and not the question we want — leave the current question
        // in place. Callers reset `isPolling` themselves.
        return;
      }

      set((state) => {
        const nextKnown = Math.max(state.knownQuestionsCount + 1, state.answeredCount + 1);
        // Deep-review #4: reconcile `answeredCount` from the SERVED ordinal.
        // The server owns the true position; `questionNumber` is the 1-based
        // ordinal of the question it just served, so exactly `questionNumber-1`
        // questions have been answered. Trusting the FE-local counter alone let
        // a silently-dropped duplicate `/quiz/next` shift all later history by
        // one. We only move `answeredCount` FORWARD to it (never rewind a
        // locally-counted answer the server hasn't yet reflected).
        const answeredCount =
          typeof servedNumber === 'number' && servedNumber >= 1
            ? Math.max(state.answeredCount, servedNumber - 1)
            : state.answeredCount;
        return {
          ...state,
          status: 'active',
          currentView: 'question',
          viewData: question,
          knownQuestionsCount: nextKnown,
          answeredCount,
          isPolling: false,
          retryCount: 0,
          // Deep-review #7/#8: clear any stale transient poll error on a
          // successful question hydration so it never lingers under the next
          // question. `clearError` previously had zero prod call sites.
          uiError: null,
          uiErrorCode: null,
          uiErrorTraceId: null,
        };
      });
      setTimeout(() => get().persistToSession(), 0);
      return;
    }

    if (IS_DEV) {
      console.warn('[QuizStore] hydrateStatus no-op (processing/unknown)', dto);
    }
  },

  beginPolling: async (_options = {}) => {
    const state = get();
    if (!state.quizId) return;
    if (state.isPolling) return;

    // AC-FE-POLL-PROD-1: install a fresh AbortController. Any prior in-flight
    // poll is aborted defensively (the isPolling guard above already prevents
    // concurrent invocations during normal flow, but reset()/error paths can
    // still leave a stale controller behind).
    abortActivePoll('begin-poll');
    const controller = new AbortController();
    activePollController = controller;

    // Deep-review #5: bind this poll session to the quizId that was current at
    // `beginPolling` time. If the store's quizId changes underneath us (a new
    // quiz started while this poll was in flight), any snapshot we receive
    // belongs to the OLD quiz and must be dropped — otherwise it hijacks the
    // new quiz (wrong question/result under the new quiz's URL).
    const capturedQuizId = get().quizId;

    set({ isPolling: true });

    const doPoll = async (): Promise<void> => {
      const { quizId, knownQuestionsCount, retryCount, status } = get();
      if (!quizId || status !== 'active') {
        set({ isPolling: false });
        if (activePollController === controller) activePollController = null;
        return;
      }

      try {
        const snapshot = await api.pollQuizStatus(quizId, {
          knownQuestionsCount,
          signal: controller.signal,
        });

        // Deep-review #5: identity guard. If the active quiz changed while this
        // request was in flight, drop the stale snapshot without applying it.
        if (get().quizId !== capturedQuizId) {
          if (IS_DEV) {
            console.warn('[QuizStore] dropping stale poll snapshot (quiz changed)', {
              capturedQuizId,
              currentQuizId: get().quizId,
            });
          }
          if (activePollController === controller) activePollController = null;
          return;
        }

        if (snapshot.status === 'finished') {
          get().hydrateStatus(snapshot);
          set({ isPolling: false, retryCount: 0, pollFailureStreak: 0 });
          if (activePollController === controller) activePollController = null;
          return;
        }

        if (snapshot.status === 'active' && snapshot.type === 'question') {
          get().hydrateStatus(snapshot);
          set({ isPolling: false, retryCount: 0, pollFailureStreak: 0 });
          if (activePollController === controller) activePollController = null;
          return;
        }

        // AC-FE-RELY-POLL-1: any successful poll (incl. processing) resets the
        // failure streak so subsequent transient failures restart at base delay.
        if (get().pollFailureStreak !== 0) {
          set({ pollFailureStreak: 0 });
        }

        const nextRetry = Math.min(retryCount + 1, MAX_RETRIES);
        set({ retryCount: nextRetry });

        const baseDelay = RETRY_DELAY_MS * (1 + Math.floor((nextRetry - 1) / 2));
        const delay = clampPollDelay(baseDelay);
        setTimeout(() => {
          set({ isPolling: false });
          get().beginPolling({ reason: 'continue' });
        }, delay);
      } catch (err: any) {
        // AC-FE-POLL-PROD-1: a benign abort (reset/new-quiz/superseded) must not
        // surface as a user-visible error.
        if (err?.canceled || err?.code === 'canceled' || controller.signal.aborted) {
          if (IS_DEV) console.warn('[QuizStore] beginPolling aborted (benign)', err);
          set({ isPolling: false });
          if (activePollController === controller) activePollController = null;
          return;
        }
        if (IS_DEV) console.error('[QuizStore] beginPolling error', err);
        const statusCode = err?.status as number | undefined;
        // Whimsical-error-system (2026-06-30): carry the backend's `QF-...` code
        // + trace id onto every fatal error so the error view shows the code as
        // light-grey small text.
        const errMeta = {
          code: (err as ApiError | undefined)?.qfCode ?? null,
          traceId: (err as ApiError | undefined)?.traceId ?? null,
        };

        if (statusCode === 404 || statusCode === 403) {
          // AC-FE-RELY-POLL-4: terminal — session is gone.
          get().setError(
            (err as ApiError | undefined)?.whimsical ||
              'Your session has expired. Please start a new quiz.',
            true,
            errMeta,
          );
          clearQuizId();
          set({ isPolling: false, pollFailureStreak: 0 });
          return;
        }

        // Schema mismatch (deploy skew / wrong-shape response): fatal-fast.
        // It has status 0 and would otherwise be treated as a transient network
        // error and burn MAX_RETRIES; retrying an unparseable payload never
        // recovers. (Additive backend fields are tolerated by the schema, so
        // this only fires on a genuine shape break.)
        if (err?.code === 'schema_error') {
          get().setError('We hit an unexpected response from the server. Please start a new quiz.', true);
          set({ isPolling: false, pollFailureStreak: 0 });
          return;
        }

        // AC-FE-RELY-POLL-2: 5xx, 429 and network failures are RETRIABLE with
        // exponential backoff. Only become fatal after MAX_RETRIES consecutive
        // failures so a transient BE blip does not kill the user's quiz.
        // 408/poll_timeout is ALSO transient (P1): pollQuizStatus throws it
        // after a 60s window, but the agent is legitimately allowed ~90s+ on
        // slow finalization. Treating it as fatal dead-ended the user and
        // discarded all progress; instead resume polling for another window.
        const isTransientFailure =
          !statusCode ||
          statusCode >= 500 ||
          statusCode === 429 ||
          statusCode === 408 ||
          err?.code === 'poll_timeout';
        const nextStreak = get().pollFailureStreak + 1;
        const isFatal = isTransientFailure
          ? nextStreak > MAX_RETRIES
          : true; // 4xx (other than 404/403) is unrecoverable
        const nextRetry = Math.min(get().retryCount + 1, MAX_RETRIES);
        const message =
          err?.code === 'poll_timeout'
            ? 'Request timed out'
            : (err as ApiError | undefined)?.whimsical ||
              err?.message ||
              'An unknown error occurred';

        // Deep-review #8: only FATAL failures may plant a user-visible
        // `uiError`. A transient failure (5xx/429/timeout below the retry cap)
        // must stay internal to the retry loop — otherwise a single blip
        // permanently rendered a stale error under every subsequent question
        // because `clearError` had zero prod call sites. The next successful
        // poll (hydrateStatus) is what clears the field.
        if (isFatal) {
          get().setError(message, isFatal, errMeta);
        }

        if (!isFatal) {
          set({ retryCount: nextRetry, pollFailureStreak: nextStreak });
          // AC-FE-PERF-POLL-1: honour server-driven Retry-After (already
          // surfaced by apiService.normalizeHttpError as `retryAfterMs`).
          const retryAfterMs = (err && typeof err === 'object' && 'retryAfterMs' in err)
            ? Number((err as { retryAfterMs?: number }).retryAfterMs) || 0
            : 0;
          const delay = isTransientFailure
            ? failureBackoffDelay(nextStreak, RETRY_DELAY_MS, retryAfterMs)
            : clampPollDelay(
                RETRY_DELAY_MS * (1 + Math.floor((nextRetry - 1) / 2)),
                retryAfterMs,
              );
          setTimeout(() => {
            set({ isPolling: false });
            get().beginPolling({ reason: 'retry' });
          }, delay);
        } else {
          set({ isPolling: false, pollFailureStreak: 0 });
        }
      }
    };

    await doPoll();
  },

  markAnswered: () => {
    set((state) => ({ answeredCount: state.answeredCount + 1 }));
    setTimeout(() => get().persistToSession(), 0);
  },

  submitAnswerStart: () => set({ isSubmittingAnswer: true }),
  submitAnswerEnd: () => set({ isSubmittingAnswer: false }),

  setError: (message, isFatal = false, meta) =>
    set((state) => ({
      uiError: message,
      uiErrorCode: meta?.code ?? null,
      uiErrorTraceId: meta?.traceId ?? null,
      status: isFatal ? 'error' : state.status,
      currentView: isFatal ? 'error' : state.currentView,
      isSubmittingAnswer: false,
    })),

  clearError: () => set({ uiError: null, uiErrorCode: null, uiErrorTraceId: null }),

  mergeMediaSnapshot: (snapshot) => {
    if (!snapshot) return;
    set((state) => {
      // Additive merge: keep any URL we already resolved; only fill in new ones.
      let changed = false;
      const nextChars: Record<string, string> = { ...state.characterImages };
      if (Array.isArray(snapshot.characters)) {
        for (const c of snapshot.characters) {
          if (c && c.name && c.imageUrl && !nextChars[c.name]) {
            nextChars[c.name] = c.imageUrl;
            changed = true;
          }
        }
      }
      const nextSyn = state.synopsisImageUrl ?? snapshot.synopsisImageUrl ?? null;
      const nextRes = state.resultImageUrl ?? snapshot.resultImageUrl ?? null;
      if (nextSyn !== state.synopsisImageUrl) changed = true;
      if (nextRes !== state.resultImageUrl) changed = true;
      if (!changed) return state; // no-op (avoids a needless re-render)
      return {
        ...state,
        characterImages: nextChars,
        synopsisImageUrl: nextSyn,
        resultImageUrl: nextRes,
      };
    });
  },

  recover: () =>
    set((state) => ({
      status: state.status === 'error' ? 'idle' : state.status,
      currentView: state.currentView === 'error' ? 'idle' : state.currentView,
      uiError: null,
      uiErrorCode: null,
      uiErrorTraceId: null,
      retryCount: 0,
    })),

  reset: () => {
    // AC-FE-POLL-PROD-1: abort any in-flight poll so a late response cannot
    // re-hydrate the freshly reset store.
    abortActivePoll('reset');
    clearQuizId();
    // Deep-review #3: set `quizId: null` explicitly (rather than relying on it
    // being absent from `initialState`) so the invariant is obvious at the call
    // site and survives any future edit to `initialState`.
    set({ ...initialState, quizId: null });
  },

  persistToSession: () => {
    const state = get();
    const now = Date.now();

    if (now - state.lastPersistTime < MIN_SESSION_PERSIST_INTERVAL_MS) return;
    if (!state.quizId || (state.status !== 'active' && state.status !== 'finished')) return;

    const snapshot: PersistedSnapshot = {
      quizId: state.quizId,
      currentView: state.currentView as 'synopsis' | 'question' | 'result',
      answeredCount: state.answeredCount,
      knownQuestionsCount: state.knownQuestionsCount,
    };

    // Deep-review #14: on the synopsis screen, persist the full synopsis
    // viewData (title/summary/characters) so a refresh can be restored locally
    // without a poll — the paid synopsis + characters generation is otherwise
    // discarded because `/quiz/status` has no synopsis shape.
    if (state.currentView === 'synopsis' && state.viewData) {
      snapshot.synopsis = state.viewData as Synopsis & { characters?: unknown };
      // Reinterpret reload: persist the typed topic + rejected readings so the
      // subtle affordance (and its accumulated chain) survives a refresh.
      snapshot.category = state.category;
      snapshot.rejectedInterpretations = state.rejectedInterpretations;
    }

    saveQuizState(snapshot);
    set({ lastPersistTime: now });

    if (IS_DEV) console.warn('[QuizStore] Persisted to session', snapshot);
  },

  recoverFromSession: async () => {
    const state = get();
    if (state.sessionRecovered || state.status !== 'idle') return false;

    const savedState = getQuizState() as PersistedSnapshot | null;
    const savedQuizId = getQuizId();
    if (!savedState || !savedQuizId) return false;

    if (IS_DEV) console.warn('[QuizStore] Attempting session recovery', savedState);

    // Deep-review #14: the synopsis screen has no `/quiz/status` shape, so
    // recovering it by polling would spin `processing` into a fatal 60s-timeout
    // loop and throw away the paid synopsis + characters. If we persisted the
    // synopsis viewData, restore it LOCALLY and resume at the synopsis screen
    // with no network call. The user can then proceed exactly as before.
    if (savedState.currentView === 'synopsis' && savedState.synopsis) {
      set({
        quizId: savedQuizId,
        currentView: 'synopsis',
        viewData: savedState.synopsis as Synopsis,
        answeredCount: savedState.answeredCount,
        knownQuestionsCount: savedState.knownQuestionsCount,
        status: 'active',
        sessionRecovered: true,
        uiError: null,
        uiErrorCode: null,
        uiErrorTraceId: null,
        // Reinterpret reload: restore the topic + rejected-reading chain so
        // the affordance keeps working (and keeps its cap) after a refresh.
        category: typeof savedState.category === 'string' ? savedState.category : null,
        rejectedInterpretations: Array.isArray(savedState.rejectedInterpretations)
          ? savedState.rejectedInterpretations.filter((s): s is string => typeof s === 'string')
          : [],
      });
      if (IS_DEV) console.warn('[QuizStore] Session recovered (synopsis, local)');
      return true;
    }

    try {
      // Deep-review #3/#6: re-serve the UNANSWERED on-screen question by asking
      // the server for `known_questions_count = answeredCount`. The server
      // serves `max(answered_idx, known_questions_count)`; passing the saved
      // `knownQuestionsCount` (typically answeredCount+1) would skip the current
      // question and misattribute the user's next answer. `answeredCount` is the
      // 0-based index of the question the user was looking at.
      const currentStatus = await api.getQuizStatus(savedQuizId, {
        knownQuestionsCount: savedState.answeredCount,
      });

      if (currentStatus.status === 'processing' || currentStatus.status === 'active') {
        set({
          quizId: savedQuizId,
          currentView: savedState.currentView,
          answeredCount: savedState.answeredCount,
          // Deep-review #3/#6: seed `knownQuestionsCount` to `answeredCount` so a
          // subsequent `beginPolling` (the processing branch below) also asks the
          // server to re-serve the CURRENT unanswered question rather than n+1.
          knownQuestionsCount: savedState.answeredCount,
          status: 'active',
          sessionRecovered: true,
          uiError: null,
          uiErrorCode: null,
          uiErrorTraceId: null,
        });

        if (currentStatus.status === 'active' && currentStatus.type === 'question') {
          get().hydrateStatus(currentStatus);
        } else {
          get().beginPolling({ reason: 'recover' });
        }
        if (IS_DEV) console.warn('[QuizStore] Session recovered (active/processing)');
        return true;
      }

      if (currentStatus.status === 'finished') {
        set({
          quizId: savedQuizId,
          status: 'finished',
          currentView: 'result',
          viewData: normalizeResultLike(currentStatus.data),
          sessionRecovered: true,
          uiError: null,
          uiErrorCode: null,
          uiErrorTraceId: null,
        });
        if (IS_DEV) console.warn('[QuizStore] Session recovered (finished)');
        return true;
      }
    } catch (err) {
      if (IS_DEV) console.error('[QuizStore] Failed to recover session', err);
      clearQuizId();
    }
    return false;
  },
});

export const useQuizStore = create<QuizStore>()(
  devtools(storeCreator, {
    name: 'quiz-store',
    enabled: IS_DEV,
  })
);

export const useQuizView = () =>
  useQuizStore(
    useShallow((s) => ({
      quizId: s.quizId,
      currentView: s.currentView,
      viewData: s.viewData,
      status: s.status,
      isPolling: s.isPolling,
      isSubmittingAnswer: s.isSubmittingAnswer,
      uiError: s.uiError,
      uiErrorCode: s.uiErrorCode,
      uiErrorTraceId: s.uiErrorTraceId,
    }))
  );

export const useQuizProgress = () =>
  useQuizStore(
    useShallow((s) => ({
      answeredCount: s.answeredCount,
      totalTarget: s.totalTarget,
    }))
  );

export const useQuizActions = () =>
  useQuizStore(
    useShallow((s) => ({
      startQuiz: s.startQuiz,
      reinterpret: s.reinterpret,
      hydrateFromStart: s.hydrateFromStart,
      hydrateStatus: s.hydrateStatus,
      beginPolling: s.beginPolling,
      markAnswered: s.markAnswered,
      submitAnswerStart: s.submitAnswerStart,
      submitAnswerEnd: s.submitAnswerEnd,
      setError: s.setError,
      clearError: s.clearError,
      recover: s.recover,
      reset: s.reset,
      persistToSession: s.persistToSession,
      recoverFromSession: s.recoverFromSession,
      mergeMediaSnapshot: s.mergeMediaSnapshot,
    }))
  );

/**
 * Blackbox fix #4(b) — read the persisted async image URLs (cast thumbnails +
 * synopsis/result heroes) so they survive a view change and show through to the
 * result page.
 */
/**
 * "Try a different interpretation" (2026-07-02) — the synopsis screen's subtle
 * reload affordance reads the typed topic (affordance hidden without one) and
 * the in-flight guard.
 */
export const useReinterpretState = () =>
  useQuizStore(
    useShallow((s) => ({
      category: s.category,
      isReinterpreting: s.isReinterpreting,
    }))
  );

export const useQuizMediaStore = () =>
  useQuizStore(
    useShallow((s) => ({
      characterImages: s.characterImages,
      synopsisImageUrl: s.synopsisImageUrl,
      resultImageUrl: s.resultImageUrl,
    }))
  );

if (typeof window !== 'undefined') {
  const savedQuizId = getQuizId();
  if (savedQuizId) {
    setTimeout(() => {
      const store = useQuizStore.getState();
      // Deep-review #3: the store now boots with `quizId: null` (it is no longer
      // prefilled from sessionStorage), so this guard actually fires. Recover
      // when a saved quiz exists, the store is still idle, and we have not
      // already recovered — `recoverFromSession` itself re-checks these to stay
      // idempotent. Previously `!store.quizId` could never be true (the store
      // pre-filled quizId from the same sessionStorage), so recovery was DEAD
      // CODE and a mid-quiz refresh dead-ended on an eternal LoadingCard.
      if (!store.quizId && store.status === 'idle' && !store.sessionRecovered) {
        store.recoverFromSession();
      }
    }, 100);
  }
}
